---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Start Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Ensure Nginx is running
  ansible.builtin.wait_for:
    port: 80
    state: started

#- name: Replace Ngnix def config
#  copy:
#    src: files/default
#    dest: /etc/ngnix/sites-enabled/default
#    owner: root
#    group: root
#    mode: 0644

#- name: Restart ngnix serv
#  service:
#    name: ngnix
#    state: restarted

#- name: start ngnix
#  service:
#    name: ngnix
#    enabled: yes
#    state: started
#
