---
- name: Install haproxy
  apt:
    name: haproxy
    state: latest

- name: put haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy


- name: Enable haproxy
  service:
    name: haproxy
    state: started
    enabled: yes

- name: haproxy exporter
  apt:
    name: prometheus-haproxy-exporter
    state: present

- name: passing ARGS
  template:
    src: prometheus-haproxy-exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: restart haproxy exporter

- name: start haproxy exporter
  service:
    name: prometheus-haproxy-exporter
    state: started

- name: add cname records
  nsupdate:
    key_name: "update_key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ update_key }}"
    server: "{{ item }}"
    zone: "{{ startup_name }}"
    record: "lb{{ inventory_hostname | replace('vlmalo', '') }}"
    value: "{{ inventory_hostname }}"
    type: "CNAME"
  with_items: "{{ groups['dns_master'] }}"
