---
- name: Add InfluxDB APT repository key
  apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key

- name: Add InfluxDB APT repository
  apt_repository:
    repo: deb https://repos.influxdata.com/debian stable main
    update_cache: yes

- name: Download InfluxDB package
  get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb
    dest: /usr/local/bin/influxdb_1.8.10_amd64.deb

- name: Install InfluxDB package
  apt:
    deb: /usr/local/bin/influxdb_1.8.10_amd64.deb
    update_cache: yes

- name: install telegraf
  apt:
    name: telegraf

- name: copy telegraf.conf
  template:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  notify: Restart telegraf

- name: start telegraf
  service:
    name: telegraf
    state: started
    enabled: yes

- name: copy influxdb.conf
  template:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf

- name: start influxdb
  service:
    name: influxdb
    state: started
    enabled: yes

- name: Ensure backup folder is created
  file:
    path: /home/backup/influxdb
    state: directory
    owner: backup
    mode: '0700'

- name: influxdb backup
  template:
    src: influxdb-backup
    dest: /etc/cron.d/influxdb-backup

- name: add cname records
  nsupdate:
    key_name: "update_key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ update_key }}"
    server: "{{ item }}"
    zone: "{{ startup_name }}"
    record: "influxdb"
    value: "{{ inventory_hostname }}"
    type: "CNAME"
  with_items: "{{ groups['dns_master'] }}"

- name: Download Influxdb Exporter
  get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_386
    dest: /usr/local/bin/influx_stats_exporter

- name: Set execute permissions on the InfluxDB exporter binary
  file:
    path: /usr/local/bin/influx_stats_exporter
    mode: '0755'

- name: service for influxdb-exporter
  template:
    src: influx_exporter.service
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
  notify:
    - Reload systemd

- name: Start the service
  service:
    name: prometheus-influxdb-stats-exporter
    state: started
    enabled: yes

