---
- name: Download InfluxDB package
  get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb
    dest: /usr/local/bin/influxdb_1.8.10_amd64.deb

- name: Install InfluxDB package
  apt:
    deb: /tmp/influxdb_1.8.10_amd64.deb

- name: Add InfluxDB APT repository key
  apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key

- name: Add InfluxDB APT repository
  apt_repository:
    repo: deb https://repos.influxdata.com/debian stable main

- name: install telegraf
  apt:
    name: telegraf

- name: copy telegraf.conf
  template:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  notify: Restart telegraf

- name: start telegraf
  service:
    name: telegraf
    state: started
    enabled: yes

- name: copy influxdb.conf
  template:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf

- name: start influxdb
  service:
    name: influxdb
    state: started
    enabled: yes

- name: Ensure backup folder is created
  file:
    path: /home/backup/influxdb
    state: directory
    owner: backup
    group: backup
    mode: '0755'

- name: influxdb backup
  template:
    src: influxdb-backup
    dest: /etc/cron.d/influxdb-backup

- name: add cname records
  nsupdate:
    key_name: "update_key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ update_key }}"
    server: "{{ item }}"
    zone: "{{ startup_name }}"
    record: "influxdb"
    value: "{{ inventory_hostname }}"
    type: "CNAME"
  with_items: "{{ groups['dns_master'] }}"
