---
- name: Generate repository key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: add grafana apt repository
  apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present

- name: update cache
  apt:
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Copy grafana.ini file
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart grafana

- name: Start Grafana
  systemd:
    name: grafana-server
    state: started
