---
- name: Install grafana on docker
  docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    exposed_ports: "{{ grafana_port }}"
    published_ports: "{{ grafana_port }}:3000"
    volumes:
      - /opt/grafana:/etc/grafana
    restart_policy: always

- name: Create Grafana directories
  file:
    name: "/opt/grafana/provisioning/{{ item }}"
    state: directory
  loop:
    - dashboards
    - datasources

- name: grafana.ini file
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: true
  notify: Restart grafana container

- name: Add datasource file
  template:
    src: "{{ item }}.j2"
    dest: "/opt/grafana/provisioning/datasources/{{ item }}"
  loop:
    - main_datasource.yaml
    - main_datasourceInfluxDB.yaml
    - main_datasourceTelegraf.yaml
  notify: Restart grafana container

- name: add dashboard file conf
  template:
    src: templates/main_dashboard.yaml.j2
    dest: /opt/grafana/provisioning/dashboards/sample.yaml
  notify: Restart grafana container

- name: Copy dashboard json
  copy:
    src: "{{ item }}.json"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}.json"
  loop:
    - main
    - mysql
    - syslog
  notify: Restart grafana container

- name: add cname records
  nsupdate:
    key_name: "update_key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ update_key }}"
    server: "{{ item }}"
    zone: "{{ startup_name }}"
    record: "grafana"
    value: "{{ inventory_hostname }}"
    type: "CNAME"
  with_items: "{{ groups['dns_master'] }}"
