---
- name: Generate repository key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: add grafana apt repository
  apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present

- name: update cache
  apt:
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Copy grafana.ini file
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart grafana

- name: Add datasource file
  template:
    src: "{{ item }}.j2"
    dest: "/etc/grafana/provisioning/datasources/{{ item }}"
  loop:
    - main_datasource.yaml
    - main_datasourceInfluxDB.yaml
    - main_datasourceTelegraf.yaml
  notify: Restart grafana

- name: add dashboard file conf
  template:
    src: templates/main_dashboard.yaml.j2
    dest: /etc/grafana/provisioning/dashboards/sample.yaml
  notify: Restart grafana

- name: create grafana dash dir
  file:
    path: /var/lib/grafana/dashboards
    state: directory

- name: copy dashboard json
  copy:
    src: "{{ item }}.json"
    dest: "/var/lib/grafana/dashboards/{{ item }}.json"
  loop:
    - main
    - syslog
  notify: Restart grafana

- name: Start Grafana
  systemd:
    name: grafana-server
    state: started

