---
- name: Install grafana on docker
  docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    exposed_ports: "{{ grafana_port }}"
    published_ports: "{{ grafana_port }}:3000"
    volumes:
      - /opt/grafana:/etc/grafana

- name: Create Grafana directories
  file:
    name: "/opt/grafana/provisioning/{{ item }}"
    state: directory
    recurse: yes
    mode: "0755"
  loop:
    - dashboards
    - datasources

- name: grafana.ini file
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini

- name: Add datasource file
  template:
    src: "{{ item }}.j2"
    dest: "/opt/grafana/provisioning/datasources/{{ item }}"
  loop:
    - main_datasource.yaml
    - main_datasourceInfluxDB.yaml
    - main_datasourceTelegraf.yaml

- name: add dashboard file conf
  template:
    src: templates/main_dashboard.yaml.j2
    dest: /opt/grafana/provisioning/dashboards/sample.yaml

- name: Copy dashboard json
  copy:
    src: "{{ item }}.json"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}.json"
  loop:
    - main
    - mysql
    - syslog
  notify: Restart grafana container
