---
- name: Install uWSGI packages
  apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
    state: present
    update_cache: yes

- name: Configure uWSGI for AGAMA
  copy:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: root
    group: root
    mode: '0644'
  notify: Restart uWSGI

- name: Ensure that the uwsgi is running
  service:
    name: uwsgi
    state: started
    enabled: true
