---
- name: Install uWSGI packages
  apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
    state: present
    update_cache: yes

- name: Configure uWSGI for AGAMA
  template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: '0600'
    no_log: true
  notify: Restart uWSGI

- name: Ensure that the uwsgi is running
  service:
    name: uwsgi
    state: started
    enabled: true
