---
- name: Install uwsgi
  become: yes
  ansible.builtin.apt:
    name: uwsgi
    state: latest
    update_cache: yes

- name: Install uwsgi plugin p3
  ansible.builtin.apt:
   pkg:
    - uwsgi
    - uwsgi-plugin-python3

- name: Start the uwsgi service
  service:
    name: uwsgi
    state: started
    enabled: yes

- name: change the agama config
  copy:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify: restart uwsgi

- name: ensure that uwsgi is started
  become: yes
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: yes
