---
- name: Initial setup
  hosts: all
  become: yes
  roles:
    - init

- name: Database server
  hosts: db_servers
  roles:
    - mysql

- hosts: web_servers
  become: yes
  become_user: root
  roles:
    - agama
    - uwsgi
    - nginx
