---
- name: Initial setup
  hosts: all
  become: yes
  roles:
    - init
  tags: init

- name: resolv
  hosts: resolv
  roles:
    - resolv

- name: DNS
  hosts: dns_servers
  roles:
    - bind
  tags: b

- name: prometheus
  hosts: prometheus
  roles:
    - prometheus
  tags: p

- name: Database server
  hosts: db_servers
  roles:
    - mysql
  tags: m

- name: Docker
  hosts: docker
  roles:
    - docker
  tags: docker

- hosts: web_servers
  become_user: root
  roles:
    - agama
    - nginx
  tags: agama

- name: Grafana
  hosts: grafana
  roles:
    - grafana
  tags: g

- name: Influxdb
  hosts: influxdb
  roles:
    - influxdb
    - influxdb_exporter
    - pinger
  tags: i
