---
- name: Initial setup
  become: yes
  hosts: all
  roles:
    - init
  tags: init

- name: DNS
  become: yes
  hosts: dns_servers
  roles:
    - bind
  tags: b

- name: resolv
  become: yes
  hosts: all
  roles:
    - resolv
  tags: r

- name: prometheus
  become: yes
  hosts: prometheus
  roles:
    - prometheus
  tags: p

- name: Database server
  become: yes
  hosts: db_servers
  roles:
    - mysql
  tags: m

- name: Docker
  become: yes
  hosts: docker
  roles:
    - docker
    - agama
  tags: docker

- hosts: web_servers
  become: yes
  roles:
    - nginx
  tags: nginx

- name: Grafana
  become: yes
  hosts: grafana
  roles:
    - grafana
  tags: g

- name: Influxdb
  become: yes
  hosts: influxdb
  roles:
    - influxdb
    - influxdb_exporter
    - pinger
  tags: i

- name: Keepalived
  become: yes
  hosts: keepalived
  roles:
    - keepalived
    - haproxy
  tags: k
