---
- name: Initial setup
  hosts: all
  become: yes
  roles:
    - init

- name: DNS
  hosts: dns_servers
  roles:
    - bind

- name: prometheus
  hosts: prometheus
  roles:
    - prometheus

- name: Database server
  hosts: db_servers
  roles:
    - mysql

- hosts: web_servers
  become_user: root
  roles:
    - agama
    - uwsgi
    - nginx

#- name: Grafana
#    hosts: grafana
#    roles:
#      - grafana
