{
 "title": "main",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "bind9 status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DNS queries",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes/node_memory_MemTotal_bytes*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepalived vrrp state",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "mysql status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL selects",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 5 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "1-rate(node_cpu_seconds_total{mode=\"idle\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Haproxy status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "InfluxDB status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB write rate ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 10 },
   "targets": [
    {
     "expr": "100-rate(influxdb_write_write_ok[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "docker haproxy status (vlmalo-1 exporter)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"lb-1:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "docker haproxy status (vlmalo-2 exporter)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"lb-2:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nginx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 15 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}