---
- name: Create /opt/agama
  file:
    path: /opt/agama
    state: directory

- name: Downloading AGAMA
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/{{ item }}
    dest: /opt/agama
  loop:
    - agama.py
    - Dockerfile

- name: Build the image
  docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Agama two containers
  docker_container:
    name: "agama_{{ item }}"
    image: agama
    published_ports: "{{ agama_port + item }}:8000"
    env:
      "AGAMA_DATABASE_URI": "mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}"
  loop: "{{ range(nginx_container_per_vm) }}"

- name: add cname records
  nsupdate:
    key_name: "update_key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ update_key }}"
    server: "{{ item }}"
    zone: "{{ startup_name }}"
    record: "www{{ inventory_hostname | replace('vlmalo', '') }}"
    value: "{{ inventory_hostname }}"
    type: "CNAME"
  with_items: "{{ groups['dns_master'] }}"
