---
- name: Create /opt/agama
  file:
    path: /opt/agama
    state: directory

- name: Downloading AGAMA
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/{{ item }}
    dest: /opt/agama
  loop:
    - agama.py
    - Dockerfile

- name: Build the image
  docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Agama container
  docker_container:
    name: agama
    image: agama
    published_ports: "{{ agama_port }}:8000"
    env:
      "AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}"
    restart_policy: always
