---

- name: Copy .my.cnf template to conf path
  template:
    src: .my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  notify:
      - restart mysqld exporter

- name: Copy my.cnf to home backup
  template:
    src: .my.cnf.backup.j2
    dest: /home/backup/.my.cnf
    owner: backup
    group: backup
    mode: '0400'
  notify: Restart MySQL Service
  no_log: true

- name: Install MySQL server
  apt:
    name: mysql-server
    state: present

- name: Insatll py3 mysql lib
  apt:
    name: python3-pymysql
    state: present

- name: Ensure that MySQL service is started
  systemd:
    name: mysql
    state: started
    enabled: true

- name: Copy MySQL conf
  template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySQL Service

- name: MySQL database
  mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock


- name: Install MySQL Exporter
  apt:
    name: prometheus-mysqld-exporter
    state: present

- name: update prometheus MySQL exporter
  template:
    src: prometheus-mysqld-exporter.j2
    dest: /etc/default/prometheus-mysqld-exporter
  notify: restart mysqld exporter

- name: Create mysql_exporter user
  mysql_user:
     name: "{{ mysql_exporter_user }}"
     password: "{{ mysql_exporter_password }}"
     login_unix_socket: /var/run/mysqld/mysqld.sock
     priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'



- name: Create folder for mysql backups
  file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    group: backup
    mode: '0700'

- name: Create backup user
  become: true
  mysql_user:
    name: backup
    password: "{{ mysql_backup_password }}"
    priv: "*.*:LOCK TABLES,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Upload crontab for agama backup
  template:
    src: mysql-backup
    dest: /etc/cron.d/mysql-backup

- name: create replication user
  mysql_user:
    name: "{{ mysql_replication_user }}"
    password: "{{ mysql_replication_password }}"
    host: "%"
    priv: "*.*:REPLICATION SLAVE"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: Restart MySQL Service

- name: MySQL read only mode
  mysql_variables:
    variable: read_only
    value: "{{ 'OFF' if inventory_hostname == mysql_host else 'ON' }}"
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - Reset MySQL source
    - Reset MySQL replica
