---

- name: Copy .my.cnf template to conf path
  template:
    src: .my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  notify:
      - restart mysqld exporter

- name: Install MySQL server
  apt:
    name: mysql-server
    state: present

- name: Insatll py3 mysql lib
  apt:
    name: python3-pymysql
    state: present

- name: Ensure that MySQL service is started
  systemd:
    name: mysql
    state: started
    enabled: true

- name: Copy MySQL conf
  copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySQL Service

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock


- name: Install MySQL Exporter
  apt:
    name: prometheus-mysqld-exporter
    state: present

- name: Create mysql_exporter user
  community.mysql.mysql_user:
     name: "{{ mysql_exporter_user }}"
     password: "{{ mysql_exporter_password }}"
     login_unix_socket: /var/run/mysqld/mysqld.sock
     priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'



- name: Create folder for mysql backups
  file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    group: backup

- name: Create backup user
  mysql_user:
    name: backup
    password: "{{ mysql_backup_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:LOCK TABLES,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Copy my.cnf to home backup
  copy:
    src: .my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    group: backup
  notify: Restart Mysql Service
  no_log: yes


- name: Upload crontab for agama backup
  template:
    src: mysql-backup
    dest: /etc/cron.d/mysql-backup
