---
- name: Install prometheus
  apt:
    name:
      - prometheus
    state: present

- name: start prometheus service
  service:
    name: prometheus
    state: started

- name: copy static config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: restart prometheus

- name: add conf file to /etc/default/prometheus
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify: restart prometheus
