---
- name: Restart MySQL Service
  service:
    name: mysql
    state: restarted

- name: restart mysqld exporter
  service:
    name: prometheus-mysqld-exporter
    state: restarted

- name: Reset MySQL source
  mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - resetprimary
  when: inventory_hostname == mysql_host

- name: Reset MySQL replica
  mysql_replication:
    mode: "{{ item }}"
    primary_host: "{{ mysql_host }}"
    primary_user: "{{ mysql_replication_user }}"
    primary_password: "{{ mysql_replication_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - changeprimary
    - resetreplica
    - startreplica
  when: inventory_hostname != mysql_host
  no_log: true
