---
- name: Install bind9
  apt:
    pkg:
      - bind9
      - prometheus-bind-exporter
      - python3-dnspython

- name: copy DNS conf local
  template:
    dest: /etc/bind/named.conf.local
    src: named.conf.local.j2
  no_log: true
  notify: Restart bind

- name: copy DNS conf options
  template:
    dest: /etc/bind/named.conf.options
    src: named.conf.options.j2
  no_log: true
  notify: Restart bind


- name: copy master zone database
  template:
    dest: /var/cache/bind/db.{{ startup_name }}
    src: db.talkmate.j2
    force: no
  notify: rndc bind
  when: inventory_hostname in groups['dns_master']

- name: copy rev zone database
  template:
    dest: /var/cache/bind/db.{{ startup_name }}.reverse
    src: db.talkmate.reverse
    force: no
  notify: rndc bind
  when: inventory_hostname in groups['dns_master']

- name: flush handlers
  meta: flush_handlers

- name: Start bind and exporter
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - bind9
    - prometheus-bind-exporter

- name: record
  nsupdate:
    key_name: "update_key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ update_key }}"
    server: "localhost"
    zone: "{{ startup_name }}"
    record: "backup"
    value: "{{ backup }}"
  when: inventory_hostname in groups['dns_master']

- name: set cname
  nsupdate:
    key_name: "update_key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ update_key }}"
    server: "{{ inventory_hostname }}"
    zone: "{{ startup_name }}"
    record: "ns{{ item | replace('vlmalo', '') }}"
    value: "{{ item }}"
    type: "CNAME"
  with_items: "{{ groups['dns_servers'] }}"
  when: inventory_hostname in groups['dns_master']
