---
- name: Install bind9
  apt:
    pkg:
      - bind9

- name: Ensure that bind9 is running
  service:
    name: bind9
    state: started
    enabled: yes

- name: copy DNS conf
  template:
    dest: /etc/bind/named.conf.{{ item }}
    src: named.conf.{{ item }}.j2
  loop:
    - options
    - local
  notify: Restart bind

- name: copy master zone database
  template:
    dest: /var/lib/bind/db.{{ startup_name }}
    src: db.talkmate.j2
  notify: Reload rndc
