#- name: Ansible ping module
#  ansible.builtin.ping: 

- name: Add the user juri
  ansible.builtin.user:
    name: juri

- name: Authorize juri from url
  ansible.posix.authorized_key:
    user: juri
    key: https://github.com/hudolejev.keys
    path: /home/juri/.ssh/authorized_keys

- name: Add the user roman
  ansible.builtin.user:
    name: roman

- name: Authorize roman from url
  ansible.posix.authorized_key:
    user: roman
    key: https://github.com/romankuchin.keys
    path: /home/roman/.ssh/.authorized_keys

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400
