#- name: Ansible ping module
#  ansible.builtin.ping: 

#- name: Add the user juri
#  ansible.builtin.user:
#    name: juri

#- name: Authorize juri from url
#  ansible.posix.authorized_key:
#    user: juri
#    key: https://github.com/hudolejev.keys
#    path: /home/juri/.ssh/authorized_keys

#- name: Add the user roman
#  ansible.builtin.user:
#    name: roman

#- name: Authorize roman from url
#  ansible.posix.authorized_key:
#    user: roman
#    key: https://github.com/romankuchin.keys
#    path: /home/roman/.ssh/.authorized_keys

- name: Update APT cache
  apt:
    cache_valid_time: 86400

- name: download node-exporter
  apt:
    name: prometheus-node-exporter
    state: present

- name: Update CA certificates
  apt:
    name: ca-certificates=20230311ubuntu0.20.04.1

- name: Install Rsyslog
  apt:
    name: rsyslog
    state: latest

- name: conf rsyslog
  template:
    src: 51-telegraf.conf
    dest: /etc/rsyslog.d/51-telegraf.conf
    mode: '0777'
  notify: Restart Rsyslog

- name: Start rsyslog
  service:
    name: rsyslog
    state: started
    enabled: yes

- name: Add backup user
  user:
    name: backup
    group: backup
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: /home/backup/.ssh/id_rsa

- name: known_hosts file for backup user
  template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: '0700'

- name: Ensure folder is created
  file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: backup
    mode: '0700'

- name: Install duplicity
  apt:
    name: duplicity
    state: latest

- name: Enable prometheus-node-exporter
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes
